version: '3'

services:
  upload_service:
    build: ./upload_service
    volumes:
      - './upload_service/app:/upload_service/app'
    ports:
      - 3000:80
    environment:
      MONGODB_HOSTNAME: localhost
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend

  map_service:
    build: ./map_service
    volumes:
      - './upload_service/app:/upload_service/app'
    ports:
      - 5000:80
      - 8080:8080
    environment:
      MONGODB_HOSTNAME: localhost
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGODB_HOST:  localhost
      MONGODB_HOSTNAME:  localhost
      MONGODB_PORT: 27017
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
